language: perl
install: cpanm --quiet --installdeps --with-develop --notest .
perl:
    - "5.22"
    - "5.24"
    - "5.24-shrplib"
    - "5.26"
    - "5.28"
    - "5.30"
notifications:
    on_success: never
    on_failure: always

